uploads = []

[[generated]]
id = "ji4N2WUPjSa5cVuo2pvIg"
uri = "file://artifacts/cbst-mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "q9Ug9sMCT99z9F3AGRjck"
uri = "file://artifacts/hedge-fund-ai/public/images/aebida-logo-dark.png"
type = "image"
title = "generated_image"

[[generated]]
id = "DMq4iioiqA2BUOwBzm4Uz"
uri = "file://artifacts/hedge-fund-ai/public/images/aebida-logo-light.png"
type = "image"
title = "generated_image"

[[generated]]
id = "QRzIS6Hm_wplR0EfLZ6C9"
uri = "file://artifacts/hedge-fund-ai/public/opengraph.png"
type = "image"
title = "aibitda og card"

[[outputs]]
id = "PpFX1Gbi2vvjgCMqPoTmA"
uri = "file://artifacts/hedge-fund-ai/public/pwa-512x512.png"
type = "image"
title = "애빛다 앱 아이콘"
