export interface KRTicker { ticker: string; name: string; market: "KOSPI" | "KOSDAQ" }
export interface USTicker { ticker: string; name: string; index: "SP500" | "NASDAQ100" }

export const KR_UNIVERSE: KRTicker[] = [
  // ── KOSPI 주요 종목 ──────────────────────────────────────────────
  { ticker: "005930", name: "삼성전자",        market: "KOSPI" },
  { ticker: "000660", name: "SK하이닉스",       market: "KOSPI" },
  { ticker: "005380", name: "현대자동차",       market: "KOSPI" },
  { ticker: "207940", name: "삼성바이오로직스", market: "KOSPI" },
  { ticker: "006400", name: "삼성SDI",          market: "KOSPI" },
  { ticker: "068270", name: "셀트리온",         market: "KOSPI" },
  { ticker: "005490", name: "POSCO홀딩스",      market: "KOSPI" },
  { ticker: "051910", name: "LG화학",           market: "KOSPI" },
  { ticker: "035420", name: "NAVER",            market: "KOSPI" },
  { ticker: "035720", name: "카카오",           market: "KOSPI" },
  { ticker: "003550", name: "LG",               market: "KOSPI" },
  { ticker: "028260", name: "삼성물산",         market: "KOSPI" },
  { ticker: "086790", name: "하나금융지주",     market: "KOSPI" },
  { ticker: "105560", name: "KB금융",           market: "KOSPI" },
  { ticker: "055550", name: "신한지주",         market: "KOSPI" },
  { ticker: "032830", name: "삼성생명",         market: "KOSPI" },
  { ticker: "096770", name: "SK이노베이션",     market: "KOSPI" },
  { ticker: "003670", name: "포스코퓨처엠",     market: "KOSPI" },
  { ticker: "010950", name: "S-Oil",            market: "KOSPI" },
  { ticker: "066570", name: "LG전자",           market: "KOSPI" },
  { ticker: "030200", name: "KT",               market: "KOSPI" },
  { ticker: "017670", name: "SK텔레콤",         market: "KOSPI" },
  { ticker: "015760", name: "한국전력",         market: "KOSPI" },
  { ticker: "034730", name: "SK",               market: "KOSPI" },
  { ticker: "000270", name: "기아",             market: "KOSPI" },
  { ticker: "012330", name: "현대모비스",       market: "KOSPI" },
  { ticker: "009540", name: "HD한국조선해양",   market: "KOSPI" },
  { ticker: "011170", name: "롯데케미칼",       market: "KOSPI" },
  { ticker: "034020", name: "두산에너빌리티",   market: "KOSPI" },
  { ticker: "032640", name: "LG유플러스",       market: "KOSPI" },
  { ticker: "004020", name: "현대제철",         market: "KOSPI" },
  { ticker: "010130", name: "고려아연",         market: "KOSPI" },
  { ticker: "036460", name: "한국가스공사",     market: "KOSPI" },
  { ticker: "023530", name: "롯데쇼핑",         market: "KOSPI" },
  { ticker: "071050", name: "한국금융지주",     market: "KOSPI" },
  { ticker: "030000", name: "제일기획",         market: "KOSPI" },
  { ticker: "011790", name: "SKC",              market: "KOSPI" },
  { ticker: "024110", name: "기업은행",         market: "KOSPI" },
  { ticker: "078930", name: "GS",               market: "KOSPI" },
  { ticker: "002790", name: "아모레G",          market: "KOSPI" },
  { ticker: "004370", name: "농심",             market: "KOSPI" },
  { ticker: "009150", name: "삼성전기",         market: "KOSPI" },
  { ticker: "028050", name: "삼성엔지니어링",   market: "KOSPI" },
  { ticker: "001800", name: "오리온홀딩스",     market: "KOSPI" },
  { ticker: "011070", name: "LG이노텍",         market: "KOSPI" },
  { ticker: "042660", name: "한화오션",         market: "KOSPI" },
  { ticker: "082740", name: "한화엔진",         market: "KOSPI" },
  { ticker: "010140", name: "삼성중공업",       market: "KOSPI" },
  { ticker: "051600", name: "한전KPS",          market: "KOSPI" },
  { ticker: "073240", name: "금호타이어",       market: "KOSPI" },
  { ticker: "006280", name: "녹십자",           market: "KOSPI" },
  { ticker: "161390", name: "한국타이어앤테크놀로지", market: "KOSPI" },
  { ticker: "000120", name: "CJ대한통운",       market: "KOSPI" },
  { ticker: "011200", name: "HMM",              market: "KOSPI" },
  { ticker: "000720", name: "현대건설",         market: "KOSPI" },
  { ticker: "180640", name: "한화에어로스페이스", market: "KOSPI" },
  { ticker: "002380", name: "KCC",              market: "KOSPI" },
  { ticker: "006360", name: "GS건설",           market: "KOSPI" },
  { ticker: "003600", name: "SK케미칼",         market: "KOSPI" },
  { ticker: "043200", name: "한미반도체",       market: "KOSPI" },
  { ticker: "138040", name: "메리츠금융지주",   market: "KOSPI" },
  { ticker: "000810", name: "삼성화재",         market: "KOSPI" },
  { ticker: "047050", name: "포스코인터내셔널", market: "KOSPI" },
  { ticker: "033780", name: "KT&G",             market: "KOSPI" },
  { ticker: "000100", name: "유한양행",         market: "KOSPI" },
  { ticker: "001570", name: "금양",             market: "KOSPI" },
  { ticker: "003490", name: "대한항공",         market: "KOSPI" },
  { ticker: "088350", name: "한화생명",         market: "KOSPI" },
  { ticker: "001040", name: "CJ",               market: "KOSPI" },
  { ticker: "010060", name: "OCI홀딩스",        market: "KOSPI" },
  { ticker: "004170", name: "신세계",           market: "KOSPI" },
  { ticker: "000210", name: "DL",               market: "KOSPI" },
  { ticker: "001530", name: "DI동일",           market: "KOSPI" },
  { ticker: "021240", name: "코웨이",           market: "KOSPI" },
  { ticker: "004990", name: "롯데지주",         market: "KOSPI" },
  { ticker: "000080", name: "하이트진로",       market: "KOSPI" },
  { ticker: "002440", name: "금호석유",         market: "KOSPI" },
  { ticker: "000140", name: "하이트진로홀딩스", market: "KOSPI" },
  { ticker: "008770", name: "호텔신라",         market: "KOSPI" },
  { ticker: "035250", name: "강원랜드",         market: "KOSPI" },
  { ticker: "003690", name: "코리안리",         market: "KOSPI" },
  { ticker: "005300", name: "롯데칠성",         market: "KOSPI" },
  { ticker: "015020", name: "이스타코",         market: "KOSPI" },
  { ticker: "267260", name: "현대일렉트릭",     market: "KOSPI" },
  { ticker: "016360", name: "삼성증권",         market: "KOSPI" },
  { ticker: "009830", name: "한화솔루션",       market: "KOSPI" },
  { ticker: "010620", name: "현대미포조선",     market: "KOSPI" },
  { ticker: "000240", name: "한국타이어앤테크",  market: "KOSPI" },
  { ticker: "271560", name: "오리온",           market: "KOSPI" },
  { ticker: "036570", name: "엔씨소프트",       market: "KOSPI" },
  { ticker: "251270", name: "넷마블",           market: "KOSPI" },
  { ticker: "402340", name: "SK스퀘어",         market: "KOSPI" },
  { ticker: "012450", name: "한화에어로스페이스", market: "KOSPI" },
  { ticker: "019170", name: "신풍제약",         market: "KOSPI" },
  { ticker: "008060", name: "대덕전자",         market: "KOSPI" },
  { ticker: "064350", name: "현대로템",         market: "KOSPI" },
  { ticker: "010520", name: "한국가스공사",     market: "KOSPI" },
  { ticker: "072130", name: "유엔젤",           market: "KOSPI" },
  { ticker: "302440", name: "SK바이오사이언스", market: "KOSPI" },
  { ticker: "145990", name: "삼양사",           market: "KOSPI" },
  // ── KOSDAQ 주요 종목 ──────────────────────────────────────────────
  { ticker: "247540", name: "에코프로비엠",     market: "KOSDAQ" },
  { ticker: "086520", name: "에코프로",         market: "KOSDAQ" },
  { ticker: "285130", name: "SK바이오사이언스", market: "KOSDAQ" },
  { ticker: "145020", name: "휴젤",             market: "KOSDAQ" },
  { ticker: "091990", name: "셀트리온헬스케어", market: "KOSDAQ" },
  { ticker: "293490", name: "카카오게임즈",     market: "KOSDAQ" },
  { ticker: "112040", name: "위메이드",         market: "KOSDAQ" },
  { ticker: "042700", name: "한미반도체",       market: "KOSDAQ" },
  { ticker: "196170", name: "알테오젠",         market: "KOSDAQ" },
  { ticker: "263750", name: "펄어비스",         market: "KOSDAQ" },
  { ticker: "035760", name: "CJ ENM",           market: "KOSDAQ" },
  { ticker: "036930", name: "주성엔지니어링",   market: "KOSDAQ" },
  { ticker: "064760", name: "티씨케이",         market: "KOSDAQ" },
  { ticker: "028300", name: "HLB",              market: "KOSDAQ" },
  { ticker: "095660", name: "네오위즈",         market: "KOSDAQ" },
  { ticker: "066970", name: "엘앤에프",         market: "KOSDAQ" },
  { ticker: "051500", name: "CJ씨푸드",         market: "KOSDAQ" },
  { ticker: "214150", name: "클래시스",         market: "KOSDAQ" },
  { ticker: "122900", name: "아이엔지생명",     market: "KOSDAQ" },
  { ticker: "326030", name: "SK바이오팜",       market: "KOSDAQ" },
  { ticker: "357780", name: "솔브레인",         market: "KOSDAQ" },
  { ticker: "018290", name: "레이",             market: "KOSDAQ" },
  { ticker: "049630", name: "재영솔루텍",       market: "KOSDAQ" },
  { ticker: "051360", name: "토비스",           market: "KOSDAQ" },
  { ticker: "078790", name: "상아프론테크",     market: "KOSDAQ" },
  { ticker: "240810", name: "원익IPS",          market: "KOSDAQ" },
  { ticker: "039030", name: "이오테크닉스",     market: "KOSDAQ" },
  { ticker: "237690", name: "에스티팜",         market: "KOSDAQ" },
  { ticker: "166090", name: "하나머티리얼즈",   market: "KOSDAQ" },
  { ticker: "048260", name: "오스템임플란트",   market: "KOSDAQ" },
  { ticker: "323410", name: "카카오뱅크",       market: "KOSDAQ" },
  { ticker: "056450", name: "한미약품",         market: "KOSDAQ" },
  { ticker: "105840", name: "셀트리온제약",     market: "KOSDAQ" },
  { ticker: "258520", name: "케이스랩코리아",   market: "KOSDAQ" },
  { ticker: "014620", name: "성광벤드",         market: "KOSDAQ" },
  { ticker: "039200", name: "오스코텍",         market: "KOSDAQ" },
  { ticker: "018880", name: "한온시스템",       market: "KOSDAQ" },
  { ticker: "083650", name: "비에이치",         market: "KOSDAQ" },
  { ticker: "041510", name: "에스엠",           market: "KOSDAQ" },
  { ticker: "352820", name: "하이브",           market: "KOSDAQ" },
  { ticker: "035900", name: "JYP Ent.",         market: "KOSDAQ" },
  { ticker: "122870", name: "와이지엔터테인먼트", market: "KOSDAQ" },
  { ticker: "060280", name: "큐렉소",           market: "KOSDAQ" },
  { ticker: "137310", name: "바이오노트",       market: "KOSDAQ" },
  { ticker: "009900", name: "코미코",           market: "KOSDAQ" },
  { ticker: "032190", name: "다우기술",         market: "KOSDAQ" },
  { ticker: "011000", name: "성보화학",         market: "KOSDAQ" },
  { ticker: "048410", name: "현대바이오",       market: "KOSDAQ" },
  { ticker: "211270", name: "AP시스템",         market: "KOSDAQ" },
  { ticker: "078600", name: "대주전자재료",     market: "KOSDAQ" },
];

export const US_UNIVERSE: USTicker[] = [
  // ── NASDAQ 100 ───────────────────────────────────────────────────
  { ticker: "AAPL",  name: "Apple",               index: "NASDAQ100" },
  { ticker: "MSFT",  name: "Microsoft",            index: "NASDAQ100" },
  { ticker: "NVDA",  name: "NVIDIA",               index: "NASDAQ100" },
  { ticker: "AMZN",  name: "Amazon",               index: "NASDAQ100" },
  { ticker: "META",  name: "Meta Platforms",       index: "NASDAQ100" },
  { ticker: "TSLA",  name: "Tesla",                index: "NASDAQ100" },
  { ticker: "GOOGL", name: "Alphabet A",           index: "NASDAQ100" },
  { ticker: "GOOG",  name: "Alphabet C",           index: "NASDAQ100" },
  { ticker: "AVGO",  name: "Broadcom",             index: "NASDAQ100" },
  { ticker: "COST",  name: "Costco",               index: "NASDAQ100" },
  { ticker: "NFLX",  name: "Netflix",              index: "NASDAQ100" },
  { ticker: "AMD",   name: "Advanced Micro Devices", index: "NASDAQ100" },
  { ticker: "QCOM",  name: "Qualcomm",             index: "NASDAQ100" },
  { ticker: "TMUS",  name: "T-Mobile US",          index: "NASDAQ100" },
  { ticker: "INTU",  name: "Intuit",               index: "NASDAQ100" },
  { ticker: "CSCO",  name: "Cisco",                index: "NASDAQ100" },
  { ticker: "AMGN",  name: "Amgen",                index: "NASDAQ100" },
  { ticker: "TXN",   name: "Texas Instruments",    index: "NASDAQ100" },
  { ticker: "HON",   name: "Honeywell",            index: "NASDAQ100" },
  { ticker: "BKNG",  name: "Booking Holdings",     index: "NASDAQ100" },
  { ticker: "SBUX",  name: "Starbucks",            index: "NASDAQ100" },
  { ticker: "CMCSA", name: "Comcast",              index: "NASDAQ100" },
  { ticker: "ISRG",  name: "Intuitive Surgical",   index: "NASDAQ100" },
  { ticker: "GILD",  name: "Gilead Sciences",      index: "NASDAQ100" },
  { ticker: "VRTX",  name: "Vertex Pharma",        index: "NASDAQ100" },
  { ticker: "MELI",  name: "MercadoLibre",         index: "NASDAQ100" },
  { ticker: "PANW",  name: "Palo Alto Networks",   index: "NASDAQ100" },
  { ticker: "MU",    name: "Micron Technology",    index: "NASDAQ100" },
  { ticker: "LRCX",  name: "Lam Research",         index: "NASDAQ100" },
  { ticker: "REGN",  name: "Regeneron",            index: "NASDAQ100" },
  { ticker: "KLAC",  name: "KLA Corp",             index: "NASDAQ100" },
  { ticker: "AMAT",  name: "Applied Materials",    index: "NASDAQ100" },
  { ticker: "ADI",   name: "Analog Devices",       index: "NASDAQ100" },
  { ticker: "ASML",  name: "ASML Holding",         index: "NASDAQ100" },
  { ticker: "CDNS",  name: "Cadence Design",       index: "NASDAQ100" },
  { ticker: "CRWD",  name: "CrowdStrike",          index: "NASDAQ100" },
  { ticker: "SNPS",  name: "Synopsys",             index: "NASDAQ100" },
  { ticker: "ABNB",  name: "Airbnb",               index: "NASDAQ100" },
  { ticker: "MDLZ",  name: "Mondelez",             index: "NASDAQ100" },
  { ticker: "MAR",   name: "Marriott",             index: "NASDAQ100" },
  { ticker: "FTNT",  name: "Fortinet",             index: "NASDAQ100" },
  { ticker: "ROST",  name: "Ross Stores",          index: "NASDAQ100" },
  { ticker: "ORLY",  name: "O'Reilly Auto",        index: "NASDAQ100" },
  { ticker: "CPRT",  name: "Copart",               index: "NASDAQ100" },
  { ticker: "PCAR",  name: "PACCAR",               index: "NASDAQ100" },
  { ticker: "NXPI",  name: "NXP Semiconductors",  index: "NASDAQ100" },
  { ticker: "MNST",  name: "Monster Beverage",     index: "NASDAQ100" },
  { ticker: "ODFL",  name: "Old Dominion Freight", index: "NASDAQ100" },
  { ticker: "MCHP",  name: "Microchip Technology", index: "NASDAQ100" },
  { ticker: "FAST",  name: "Fastenal",             index: "NASDAQ100" },
  { ticker: "CSX",   name: "CSX Corp",             index: "NASDAQ100" },
  { ticker: "PAYX",  name: "Paychex",              index: "NASDAQ100" },
  { ticker: "DLTR",  name: "Dollar Tree",          index: "NASDAQ100" },
  { ticker: "VRSK",  name: "Verisk Analytics",     index: "NASDAQ100" },
  { ticker: "BIIB",  name: "Biogen",               index: "NASDAQ100" },
  { ticker: "CEG",   name: "Constellation Energy", index: "NASDAQ100" },
  { ticker: "EA",    name: "Electronic Arts",      index: "NASDAQ100" },
  { ticker: "IDXX",  name: "IDEXX Laboratories",   index: "NASDAQ100" },
  { ticker: "CTSH",  name: "Cognizant Technology", index: "NASDAQ100" },
  { ticker: "GEHC",  name: "GE HealthCare",        index: "NASDAQ100" },
  { ticker: "DXCM",  name: "DexCom",               index: "NASDAQ100" },
  { ticker: "ANSS",  name: "Ansys",                index: "NASDAQ100" },
  { ticker: "ALGN",  name: "Align Technology",     index: "NASDAQ100" },
  { ticker: "TEAM",  name: "Atlassian",            index: "NASDAQ100" },
  { ticker: "TTD",   name: "The Trade Desk",       index: "NASDAQ100" },
  { ticker: "ZS",    name: "Zscaler",              index: "NASDAQ100" },
  { ticker: "ON",    name: "ON Semiconductor",     index: "NASDAQ100" },
  { ticker: "WDAY",  name: "Workday",              index: "NASDAQ100" },
  { ticker: "PYPL",  name: "PayPal",               index: "NASDAQ100" },
  { ticker: "WBD",   name: "Warner Bros Discovery", index: "NASDAQ100" },
  { ticker: "ILMN",  name: "Illumina",             index: "NASDAQ100" },
  { ticker: "RIVN",  name: "Rivian",               index: "NASDAQ100" },
  // ── S&P 500 추가 주요 종목 ──────────────────────────────────────
  { ticker: "JPM",   name: "JPMorgan Chase",       index: "SP500" },
  { ticker: "BAC",   name: "Bank of America",      index: "SP500" },
  { ticker: "WFC",   name: "Wells Fargo",          index: "SP500" },
  { ticker: "GS",    name: "Goldman Sachs",        index: "SP500" },
  { ticker: "MS",    name: "Morgan Stanley",       index: "SP500" },
  { ticker: "BLK",   name: "BlackRock",            index: "SP500" },
  { ticker: "C",     name: "Citigroup",            index: "SP500" },
  { ticker: "USB",   name: "US Bancorp",           index: "SP500" },
  { ticker: "AXP",   name: "American Express",     index: "SP500" },
  { ticker: "BX",    name: "Blackstone",           index: "SP500" },
  { ticker: "JNJ",   name: "Johnson & Johnson",    index: "SP500" },
  { ticker: "UNH",   name: "UnitedHealth Group",   index: "SP500" },
  { ticker: "LLY",   name: "Eli Lilly",            index: "SP500" },
  { ticker: "PFE",   name: "Pfizer",               index: "SP500" },
  { ticker: "ABT",   name: "Abbott Labs",          index: "SP500" },
  { ticker: "TMO",   name: "Thermo Fisher",        index: "SP500" },
  { ticker: "DHR",   name: "Danaher",              index: "SP500" },
  { ticker: "BMY",   name: "Bristol-Myers Squibb", index: "SP500" },
  { ticker: "MRK",   name: "Merck",                index: "SP500" },
  { ticker: "CI",    name: "Cigna",                index: "SP500" },
  { ticker: "ABBV",  name: "AbbVie",               index: "SP500" },
  { ticker: "CVS",   name: "CVS Health",           index: "SP500" },
  { ticker: "MDT",   name: "Medtronic",            index: "SP500" },
  { ticker: "SYK",   name: "Stryker",              index: "SP500" },
  { ticker: "BSX",   name: "Boston Scientific",    index: "SP500" },
  { ticker: "CAT",   name: "Caterpillar",          index: "SP500" },
  { ticker: "DE",    name: "Deere & Co",           index: "SP500" },
  { ticker: "GE",    name: "GE Aerospace",         index: "SP500" },
  { ticker: "MMM",   name: "3M",                   index: "SP500" },
  { ticker: "EMR",   name: "Emerson Electric",     index: "SP500" },
  { ticker: "ETN",   name: "Eaton Corp",           index: "SP500" },
  { ticker: "ITW",   name: "Illinois Tool Works",  index: "SP500" },
  { ticker: "RTX",   name: "RTX Corp",             index: "SP500" },
  { ticker: "LMT",   name: "Lockheed Martin",      index: "SP500" },
  { ticker: "NOC",   name: "Northrop Grumman",     index: "SP500" },
  { ticker: "GD",    name: "General Dynamics",     index: "SP500" },
  { ticker: "BA",    name: "Boeing",               index: "SP500" },
  { ticker: "XOM",   name: "ExxonMobil",           index: "SP500" },
  { ticker: "CVX",   name: "Chevron",              index: "SP500" },
  { ticker: "COP",   name: "ConocoPhillips",       index: "SP500" },
  { ticker: "EOG",   name: "EOG Resources",        index: "SP500" },
  { ticker: "SLB",   name: "Schlumberger",         index: "SP500" },
  { ticker: "PSX",   name: "Phillips 66",          index: "SP500" },
  { ticker: "MPC",   name: "Marathon Petroleum",   index: "SP500" },
  { ticker: "VLO",   name: "Valero Energy",        index: "SP500" },
  { ticker: "WMT",   name: "Walmart",              index: "SP500" },
  { ticker: "TGT",   name: "Target",               index: "SP500" },
  { ticker: "HD",    name: "Home Depot",           index: "SP500" },
  { ticker: "LOW",   name: "Lowe's",               index: "SP500" },
  { ticker: "TJX",   name: "TJX Companies",        index: "SP500" },
  { ticker: "MCD",   name: "McDonald's",           index: "SP500" },
  { ticker: "YUM",   name: "Yum! Brands",          index: "SP500" },
  { ticker: "CMG",   name: "Chipotle Mexican Grill", index: "SP500" },
  { ticker: "NKE",   name: "Nike",                 index: "SP500" },
  { ticker: "LULU",  name: "Lululemon",            index: "SP500" },
  { ticker: "VZ",    name: "Verizon",              index: "SP500" },
  { ticker: "T",     name: "AT&T",                 index: "SP500" },
  { ticker: "DIS",   name: "Walt Disney",          index: "SP500" },
  { ticker: "PG",    name: "Procter & Gamble",     index: "SP500" },
  { ticker: "KO",    name: "Coca-Cola",            index: "SP500" },
  { ticker: "PEP",   name: "PepsiCo",              index: "SP500" },
  { ticker: "CL",    name: "Colgate-Palmolive",    index: "SP500" },
  { ticker: "KMB",   name: "Kimberly-Clark",       index: "SP500" },
  { ticker: "GIS",   name: "General Mills",        index: "SP500" },
  { ticker: "K",     name: "Kellanova",            index: "SP500" },
  { ticker: "CPB",   name: "Campbell Soup",        index: "SP500" },
  { ticker: "HRL",   name: "Hormel Foods",         index: "SP500" },
  { ticker: "NEE",   name: "NextEra Energy",       index: "SP500" },
  { ticker: "DUK",   name: "Duke Energy",          index: "SP500" },
  { ticker: "SO",    name: "Southern Co",          index: "SP500" },
  { ticker: "D",     name: "Dominion Energy",      index: "SP500" },
  { ticker: "AEP",   name: "American Electric",    index: "SP500" },
  { ticker: "EXC",   name: "Exelon",               index: "SP500" },
  { ticker: "XEL",   name: "Xcel Energy",          index: "SP500" },
  { ticker: "SRE",   name: "Sempra Energy",        index: "SP500" },
  { ticker: "AMT",   name: "American Tower",       index: "SP500" },
  { ticker: "PLD",   name: "Prologis",             index: "SP500" },
  { ticker: "CCI",   name: "Crown Castle",         index: "SP500" },
  { ticker: "EQIX",  name: "Equinix",              index: "SP500" },
  { ticker: "SPG",   name: "Simon Property Group", index: "SP500" },
  { ticker: "O",     name: "Realty Income",        index: "SP500" },
  { ticker: "V",     name: "Visa",                 index: "SP500" },
  { ticker: "MA",    name: "Mastercard",           index: "SP500" },
  { ticker: "BRK-B", name: "Berkshire Hathaway B", index: "SP500" },
  { ticker: "UPS",   name: "UPS",                  index: "SP500" },
  { ticker: "FDX",   name: "FedEx",                index: "SP500" },
  { ticker: "NSC",   name: "Norfolk Southern",     index: "SP500" },
  { ticker: "UNP",   name: "Union Pacific",        index: "SP500" },
  { ticker: "LIN",   name: "Linde",                index: "SP500" },
  { ticker: "APD",   name: "Air Products",         index: "SP500" },
  { ticker: "SHW",   name: "Sherwin-Williams",     index: "SP500" },
  { ticker: "ECL",   name: "Ecolab",               index: "SP500" },
  { ticker: "DD",    name: "DuPont",               index: "SP500" },
  { ticker: "DOW",   name: "Dow Inc",              index: "SP500" },
  { ticker: "CF",    name: "CF Industries",        index: "SP500" },
  { ticker: "MOS",   name: "Mosaic",               index: "SP500" },
  { ticker: "FCX",   name: "Freeport-McMoRan",     index: "SP500" },
  { ticker: "NEM",   name: "Newmont",              index: "SP500" },
  { ticker: "GOLD",  name: "Barrick Gold",         index: "SP500" },
  { ticker: "NOW",   name: "ServiceNow",           index: "SP500" },
  { ticker: "CRM",   name: "Salesforce",           index: "SP500" },
  { ticker: "ORCL",  name: "Oracle",               index: "SP500" },
  { ticker: "SAP",   name: "SAP SE",               index: "SP500" },
  { ticker: "IBM",   name: "IBM",                  index: "SP500" },
  { ticker: "ACN",   name: "Accenture",            index: "SP500" },
  { ticker: "ADBE",  name: "Adobe",                index: "SP500" },
  { ticker: "INTC",  name: "Intel",                index: "SP500" },
  { ticker: "UBER",  name: "Uber Technologies",    index: "SP500" },
  { ticker: "LYFT",  name: "Lyft",                 index: "SP500" },
  { ticker: "SHOP",  name: "Shopify",              index: "SP500" },
  { ticker: "SQ",    name: "Block (Square)",       index: "SP500" },
  { ticker: "COIN",  name: "Coinbase",             index: "SP500" },
  { ticker: "HOOD",  name: "Robinhood",            index: "SP500" },
  { ticker: "PLTR",  name: "Palantir",             index: "SP500" },
  { ticker: "SNOW",  name: "Snowflake",            index: "SP500" },
  { ticker: "DDOG",  name: "Datadog",              index: "SP500" },
  { ticker: "NET",   name: "Cloudflare",           index: "SP500" },
  { ticker: "MDB",   name: "MongoDB",              index: "SP500" },
  { ticker: "U",     name: "Unity Software",       index: "SP500" },
  { ticker: "RBLX",  name: "Roblox",               index: "SP500" },
  { ticker: "SPOT",  name: "Spotify",              index: "SP500" },
  { ticker: "PINS",  name: "Pinterest",            index: "SP500" },
  { ticker: "SNAP",  name: "Snap",                 index: "SP500" },
  { ticker: "TWTR",  name: "X (Twitter)",          index: "SP500" },
  { ticker: "DASH",  name: "DoorDash",             index: "SP500" },
  { ticker: "ABNB",  name: "Airbnb",               index: "SP500" },
  { ticker: "LYFT",  name: "Lyft",                 index: "SP500" },
  { ticker: "PATH",  name: "UiPath",               index: "SP500" },
  { ticker: "AI",    name: "C3.ai",                index: "SP500" },
  { ticker: "GTLB",  name: "GitLab",               index: "SP500" },
  { ticker: "HLT",   name: "Hilton",               index: "SP500" },
  { ticker: "MGM",   name: "MGM Resorts",          index: "SP500" },
  { ticker: "LVS",   name: "Las Vegas Sands",      index: "SP500" },
  { ticker: "WYNN",  name: "Wynn Resorts",         index: "SP500" },
  { ticker: "RCL",   name: "Royal Caribbean",      index: "SP500" },
  { ticker: "CCL",   name: "Carnival Corp",        index: "SP500" },
  { ticker: "DAL",   name: "Delta Air Lines",      index: "SP500" },
  { ticker: "UAL",   name: "United Airlines",      index: "SP500" },
  { ticker: "AAL",   name: "American Airlines",    index: "SP500" },
  { ticker: "LUV",   name: "Southwest Airlines",   index: "SP500" },
];
