import { BRAND_COLOR } from "@workspace/shared";

const colors = {
  dark: {
    text: "#e2e8f4",
    tint: BRAND_COLOR,
    background: "#0d1119",
    foreground: "#e2e8f4",
    card: "#141821",
    cardForeground: "#e2e8f4",
    primary: BRAND_COLOR,
    primaryForeground: "#ffffff",
    secondary: "#1a2030",
    secondaryForeground: "#e2e8f4",
    muted: "#1a2030",
    mutedForeground: "#64748b",
    accent: "#2a1a1a",
    accentForeground: BRAND_COLOR,
    border: "#1e2a3d",
    input: "#1e2a3d",
    up: "#ef4444",
    upBg: "#450a0a",
    down: "#3b82f6",
    downBg: "#1e3a5f",
    warning: "#f59e0b",
    success: "#22c55e",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
  },
  light: {
    text: "#0f172a",
    tint: BRAND_COLOR,
    background: "#ffffff",
    foreground: "#0f172a",
    card: "#ffffff",
    cardForeground: "#0f172a",
    primary: BRAND_COLOR,
    primaryForeground: "#ffffff",
    secondary: "#f1f5f9",
    secondaryForeground: "#334155",
    muted: "#f8fafc",
    mutedForeground: "#64748b",
    accent: "#fff1ef",
    accentForeground: "#c0463a",
    border: "#e2e8f0",
    input: "#e2e8f0",
    up: "#ef4444",
    upBg: "#fef2f2",
    down: "#3b82f6",
    downBg: "#eff6ff",
    warning: "#d97706",
    success: "#16a34a",
    destructive: "#dc2626",
    destructiveForeground: "#ffffff",
  },
  radius: 14,
};

export default colors;
