import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import analysisRouter from "./analysis.js";
import marketDataRouter from "./market-data.js";
import modelInsightsRouter from "./model-insights.js";
import newsRouter from "./news.js";
import authRouter from "./auth.js";
import feedRouter from "./feed.js";
import stockInsightsRouter from "./stock-insights.js";
import creditsRouter from "./credits.js";
import peersRouter from "./peers.js";
import tickerNotesRouter from "./ticker-notes.js";
import adminRouter from "./admin.js";
import feedbackRouter from "./feedback.js";
import supportRouter from "./support.js";
import noticesRouter from "./notices.js";
import macroRouter from "./macro.js";
import { performanceRouter } from "./performance.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use("/admin", adminRouter);
router.use(creditsRouter);
router.use("/peers", peersRouter);
router.use("/ticker-notes", tickerNotesRouter);
router.use("/analysis", analysisRouter);
router.use("/market-data", marketDataRouter);
router.use("/market-data", stockInsightsRouter);
router.use("/model-insights", modelInsightsRouter);
router.use("/feed", feedRouter);
router.use(newsRouter);
router.use(feedbackRouter);
router.use(supportRouter);
router.use(noticesRouter);
router.use(macroRouter);
router.use(performanceRouter);

export default router;
